name: Create MSA repo tag

run-name: Create MSA repo tag

on:
  #workflow_call:
  workflow_dispatch:
    inputs:
      gitops_repo:
        description: 'gitop repo url'
        required: true
        default: ""
        type: string
      gitops_branch:
        description: 'gitop repo branch'
        required: false
        default: "main"
        type: string
      version_file_path:
        description: 'msa version file path'
        required: true
        default: ""
        type: string     

jobs:          
  create-prod-jira-release:
    name: Create prod tag for latest qa version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: ./gitops
          repository: ${{ inputs.gitops_repo }}
          ref: refs/heads/${{ inputs.gitops_branch }}
          token: ${{ secrets.GH_MANAGEPACKAGE_TOKEN }}

      - name: test
        run: |
          ls -la 
          pwd
          ls -la ${{ inputs.version_file_path }}
          cat /home/runner/work/_temp/*.sh

      - name: Update msa prod tag
        working-directory: ./gitops
        run: |
          git config user.name "csna" 
          git config user.email "<>" 
          while IFS= read -r line; do
          if [[ $line == *"service-name"* ]]; then
            service_name=$(echo "$line" | awk '{print $2}')
          elif [[ $line == *"repo-name"* ]]; then
            repo_name=$(echo "$line" | awk '{print $2}')
          elif [[ $line == *"image-tag"* ]]; then
            version_tag=$(echo "$line" | awk '{print $2}')
            echo "Service Name: $service_name"
            echo "rep url: $repo_name"
            echo "version tag: $version_tag"
            git clone $repo_name ${service_name}_tag
            cd ${service_name}_tag
            pwd
            git tag -d prod
            git push --delete origin prod
            git checkout $version_tag
            git tag prod
            git push origin prod
            cd ..
          fi
          done < ${{ inputs.version_file_path }}

