name: test action
 
on:
  workflow_dispatch:
 
jobs:
  create-prod-tag:
    name: Create prod tag for latest qa version
    runs-on: ubuntu-latest
    #uses: CheongSong0320/.github/.github/workflows/create-prod-tag.yml@main
    steps:
    - name: test
      run: |
        ls -la
        ls -la .github
        ls -la .github/workflows

#    - uses: .github/workflows/create-prod-tag.yml
#      with:
#        gitops_repo: https://github.com/CheongSong0320/gitops-test.git
#        gitops_branch: dev
#        version_file_path: "prod_version.yaml"